### ISSUE TITLE
Uncaught TypeError: tmp.fileSync is not a function

### ISSUE THREAD

**Issue by mruediger** [sinkuu/atom-susave#2]
[Enter steps to reproduce below:]
1. use susave to save a file to /etc

**Atom Version**: 1.7.1
**System**: linux 4.5.0-1-ARCH
**Thrown From**: [susave](https://github.com/sinkuu/atom-susave) package, v0.2.0
### Stack Trace

Uncaught TypeError: tmp.fileSync is not a function

```
At /home/bag/.atom/packages/susave/lib/susave.coffee:52

TypeError: tmp.fileSync is not a function
    at Object.module.exports.Susave.save (/home/bag/.atom/packages/susave/lib/susave.coffee:52:22)
    at Object.module.exports.Susave.cmdSave (/home/bag/.atom/packages/susave/lib/susave.coffee:29:10)
    at atom-workspace.subscriptions.add.atom.commands.add.susave:save (/home/bag/.atom/packages/susave/lib/susave.coffee:16:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:47.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-eclectic-syntax.theme-one-light-ui)
     -0:44.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:43.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:43.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:40.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:38.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.6.0 susave:save (atom-text-editor.editor)
  2x -0:37.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:32.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:31 core:save (atom-workspace.workspace.scrollbars-visible-always.theme-eclectic-syntax.theme-one-light-ui)
  2x -0:30.6.0 core:save-as (atom-workspace.workspace.scrollbars-visible-always.theme-eclectic-syntax.theme-one-light-ui)
     -0:02.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-eclectic-syntax.theme-one-light-ui)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 susave:save (atom-workspace.workspace.scrollbars-visible-always.theme-eclectic-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-light-ui",
      "eclectic-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.14.3
auto-reveal-in-sidebar, v0.8.0
eclectic-syntax, v0.2.1
language-ansible, v0.1.3
language-vala, v0.2.0
pretty-json, v1.0.3
susave, v0.2.0

# Dev
No dev packages
```

**Comment by sinkuu** [comment]
Thanks! Old version of `tmp` package is loaded when installed susave from atom.io.
